import re
fname = input('Enter the file name:')
with open(fr'{fname}', 'r') as finput, open(r'count_fragments.fa', 'w') as file:  # open two files
    genes = finput.read()
    gene_list = genes.split('>')  # divide the whole list into several single gene information
    gene_list.remove('')  # remove the ' ' generated by separating the list with.
    recognition_seq = re.compile('GAATTC')
    for every_gene in gene_list:
        # extract the whole sequence of the gene without \n in to a list
        sequence = re.findall(r'^[ATGC]+', every_gene, re.M)  # re.M: read multi-lines
        seq = ''.join(sequence)  # make the sequence  on one line without \n
        if not recognition_seq.search(seq):  # if no recognition site found in the sequence
            continue
        else:  # if recognition site found in the sequence
            number = len(recognition_seq.findall(seq))  # number of recognition sites
            name = re.findall(r'^.*gene:([^ ]+)', every_gene)  # extract name of the gene
            add = f'>{name[0]}  {number + 1}\n{seq}\n'  # number of fragments = number + 1
            file.write(add)  # write the information into the file
            # the number showed in the file is the number of fragments
