import re
with open(r"Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa", 'r') as sc, open(r'cut_genes.fa', 'w') as file:
    genes = sc.read()
    gene_list = genes.split('>')  # divide the whole list into several single gene information
    gene_list.remove('')   # remove the ' ' generated by separating the list with >.
    recognition_seq = re.compile('GAATTC')
    for every_gene in gene_list:
        # extract the whole sequence of the gene without \n in to a list
        sequence = re.findall(r'^[ATGC]+', every_gene, re.M)   # re.M: read multi-lines
        seq = ''.join(sequence)  # make the sequence  on one line without \n
        if not recognition_seq.search(seq):  # if no recognition site found in the sequence
            continue
        else:  # if recognition site found in the sequence
            name = re.findall(r'^.*gene:([^ ]+)', every_gene)  # extract name of the gene
            add = f'>{name[0]}  {len(seq)}\n{seq}\n'
            file.write(add)
